name: Build Latex File
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Unzip files
        run: "unzip $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | head -n 1) -d ."
      - name: Build with LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: ./main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload PDF
        run: gh release upload ${{ github.run_id }} ./main.pdf
        